// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJVgZVc55AzUyNXXebON1_TrpeUaz2jsk',
    appId: '1:717301276112:web:9983e69213539f4f416dd5',
    messagingSenderId: '717301276112',
    projectId: 'swift-wheels-6a997',
    authDomain: 'swift-wheels-6a997.firebaseapp.com',
    storageBucket: 'swift-wheels-6a997.firebasestorage.app',
    measurementId: 'G-58MV9W5091',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYXlZYwRzo9sE-CujFQlSTlrKmox7_Um4',
    appId: '1:717301276112:android:3c288c141a11914a416dd5',
    messagingSenderId: '717301276112',
    projectId: 'swift-wheels-6a997',
    storageBucket: 'swift-wheels-6a997.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC5THexDhQ8uhqp25Fezv6WrR8EW7pidU',
    appId: '1:717301276112:ios:7f20dc9937b88786416dd5',
    messagingSenderId: '717301276112',
    projectId: 'swift-wheels-6a997',
    storageBucket: 'swift-wheels-6a997.firebasestorage.app',
    iosBundleId: 'com.example.carrental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC5THexDhQ8uhqp25Fezv6WrR8EW7pidU',
    appId: '1:717301276112:ios:7f20dc9937b88786416dd5',
    messagingSenderId: '717301276112',
    projectId: 'swift-wheels-6a997',
    storageBucket: 'swift-wheels-6a997.firebasestorage.app',
    iosBundleId: 'com.example.carrental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJVgZVc55AzUyNXXebON1_TrpeUaz2jsk',
    appId: '1:717301276112:web:abc82740d95d03f3416dd5',
    messagingSenderId: '717301276112',
    projectId: 'swift-wheels-6a997',
    authDomain: 'swift-wheels-6a997.firebaseapp.com',
    storageBucket: 'swift-wheels-6a997.firebasestorage.app',
    measurementId: 'G-FQXY5RK5K8',
  );
}
